mutation CheckRegistry($email: String!) {
  checkRegistry(email: $email)
}

mutation SignUpWithPassword($password: String!, $email: String!) {
  signUpWithPassword(password: $password, email: $email) {
    accessToken
    refreshToken
    idToken
    tokenType
  }
}

mutation LoginWithPassword($password: String!, $email: String!) {
  loginWithPassword(password: $password, email: $email) {
    accessToken
    refreshToken
    idToken
    tokenType
  }
}
