module.exports = {
  PRIVATE: `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJlDfH89p3dHFvcFg
qz+HGl6Hhr9n407DWPcvkZ0CsWGhRANCAATtiQdQzXUJ4Tfk6p04mLx6YlckLTPJ
eXh++XZfSyd/SyBawVBImly6ayc632sj7F9Q7pWb7YX5LlrsSvFlulCs
-----END PRIVATE KEY-----
`,
  PUBLIC: `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7YkHUM11CeE35OqdOJi8emJXJC0z
yXl4fvl2X0snf0sgWsFQSJpcumsnOt9rI+xfUO6Vm+2F+S5a7ErxZbpQrA==
-----END PUBLIC KEY-----
`,
};